version: 2
updates:

  # Maintain dependencies for Composer
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: "weekly"

  # Maintain dependencies for Dev Containers
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: "weekly"